### PR TITLE
update the myhours table for easier math

### PR DESCRIPTION
**Pull request by jsachs**

### CODE REVIEW

**Comment by mmccall** [comment]
doesn't seem to work with add row button (the add row button will append below the total and not update), I'm guessing you checked this against a pre-populated my hours?

**Comment by jsachs** [comment]
@mmccall it actually did work for me. Was your cache cleared? I'll run a few more tests on it on my end.

**Comment by mmccall** [comment]
It was my cache :(. looks better, but it isn't initializing with a total, only on change. Since a lot of time entry is rehashing last week we probably want that.  I think either on load or on ready events can handle that.

**Comment by jsachs** [comment]
@mmccall fixed.

**Pull request merged**
